apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wil42-playground
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/Junya42/anremiki-cd
    path: dev/install-dev.yaml
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: dev

